### ISSUE TITLE
The constructor in DocumentFactory needs to be protected or public

### ISSUE THREAD

**Issue by Levis92** [Levis92/proton-text#13]
The constructor in DocumentFactory is private at the moment. You could keep it private but then you would need to implement the class with the Singleton pattern. And the constructor shouldn't take any parameters. Those should be handled in the getDocument() method.

Also, documentType should be an Enum and private 😄

**Comment by luddevig** [comment]
Changed the contstructor to public. Will maybe do a singelton pattern later on.
